### ISSUE TITLE
Bughunting: mjsunit/wasm/embenchen/lua_binarytrees

### ISSUE THREAD

**Issue by ilijapavlovic** [v8mips/v8mips#318]
The test mjsunit/wasm/embenchen/lua_binarytrees fails.

```
Exit code: -10
Result: CRASH: BUS ERROR maybe alignment problem
Expected outcomes: PASS
```

Details: https://v8.mips.com/bbv8/builders/Target%20-%20edge/builds/7240/steps/Check/logs/lua_binarytrees

**Comment by ilijapavlovic** [comment]
On the board CI20 this problem cannot be reproduced.

```
+ cd <PROJECT>/v8
+ tools/run-tests.py -j6 --arch=mipsel --mode=release '--extra-flags=""' --timeout=480 --verbose --time --no-presubmit --report mjsunit/wasm/embenchen/lua_binarytrees
>>> Running tests for mipsel.release
Total: 1 tests
 *    0 tests will be skipped
 *    0 tests are expected to timeout sometimes
 *    0 tests are expected to be flaky but not crash
 *    1 tests are expected to pass
 *    0 tests are expected to fail that we won't fix
 *    0 tests are expected to fail that we should fix
No connection to distribution server; running tests locally.
[00:58|% 100|+   3|-   0]: mjsunit/wasm/embenchen/lua_binarytrees# <PROJECT>/v8/out/mipsel.release/d8 --test --random-seed=-928785870 --nohard-abort --nodead-code-elimination --nofold-constants --expose-wasm <PROJECT>/v8/test/mjsunit/mjsunit.js <PROJECT>/v8/test/mjsunit/wasm/embenchen/lua_binarytrees.js
# <PROJECT>/v8/out/mipsel.release/d8 --test --random-seed=-928785870 --turbo --nohard-abort --nodead-code-elimination --nofold-constants --expose-wasm <PROJECT>/v8/test/mjsunit/mjsunit.js <PROJECT>/v8/test/mjsunit/wasm/embenchen/lua_binarytrees.js
# <PROJECT>/v8/out/mipsel.release/d8 --test --random-seed=-928785870 --stress-opt --always-opt --nohard-abort --nodead-code-elimination --nofold-constants --expose-wasm <PROJECT>/v8/test/mjsunit/mjsunit.js <PROJECT>/v8/test/mjsunit/wasm/embenchen/lua_binarytrees.js
 Closing process pool.
Closing database connection.
[00:58|% 100|+   3|-   0]: Done--- Total time: 00:58.623 ---     
   1 (00:49.446) mjsunit/wasm/embenchen/lua_binarytrees
   2 (00:24.605) mjsunit/wasm/embenchen/lua_binarytrees
   3 (00:24.018) mjsunit/wasm/embenchen/lua_binarytrees

```

**Comment by ilijapavlovic** [comment]
An attempt to reproduce problem with following adaptation in `src/d8.cc` (disabling the transparent recovery from unaligned address exceptions for the current process):

```
...
#include <sys/sysmips.h>

#ifndef GOOGLE3
int main(int argc, char* argv[]) {
  sysmips(MIPS_FIXADE, 0);          // 0 - recovery disabled, 1 - recovery enabled
  return v8::Shell::Main(argc, argv);
}
#endif
```

When recovery is disabled, the test produces exit code -10 but description `Result: CRASH: BUS ERROR maybe alignment problem` is missing (compared with the error code on builder):

```
=== mjsunit/wasm/embenchen/lua_binarytrees ===                    
Command: <PROJECT>/v8/out/mipsel.release/d8 --test --random-seed=1931728460 --nohard-abort --nodead-code-elimination --nofold-constants --expose-wasm <PROJECT>/v8/test/mjsunit/mjsunit.js <PROJECT>/v8/test/mjsunit/wasm/embenchen/lua_binarytrees.js 
exit code: -10
--- CRASHED ---
Attempting to rerun test after failure.
=== mjsunit/wasm/embenchen/lua_binarytrees ===                    
Command: <PROJECT>/v8/out/mipsel.release/d8 --test --random-seed=1931728460 --stress-opt --always-opt --nohard-abort --nodead-code-elimination --nofold-constants --expose-wasm <PROJECT>/v8/test/mjsunit/mjsunit.js <PROJECT>/v8/test/mjsunit/wasm/embenchen/lua_binarytrees.js 
exit code: -10
--- CRASHED ---
Attempting to rerun test after failure.
=== mjsunit/wasm/embenchen/lua_binarytrees ===                    
Command: <PROJECT>/v8/out/mipsel.release/d8 --test --random-seed=1931728460 --turbo --nohard-abort --nodead-code-elimination --nofold-constants --expose-wasm <PROJECT>/v8/test/mjsunit/mjsunit.js <PROJECT>/v8/test/mjsunit/wasm/embenchen/lua_binarytrees.js 
exit code: -10
--- CRASHED ---
Attempting to rerun test after failure.
```

When recovery is enabled, the test passes.

**Comment by ilijapavlovic** [comment]
The same error message appears in https://github.com/v8mips/v8mips/issues/268

**Comment by kilvadyb** [comment]
Nice catch. All the v8 code should work without kernel unaligned fix/recover feature. Please try to find the failing code snippet with a debugger.

**Comment by ilijapavlovic** [comment]
With disabled recovery and in release mode following output is received with GDB:

```
gdb <PROJECT>/v8/out/mipsel.release/d8
...
(gdb) set args --test --random-seed=-849301947 --stress-opt --always-opt --nohard-abort --nodead-code-elimination --nofold-constants --expose-wasm <PROJECT>/v8/test/mjsunit/mjsunit.js <PROJECT>/v8/test/mjsunit/wasm/embenchen/lua_binarytrees.js
(gdb) run
...
============ Stress 1/5 ============

Program received signal SIGBUS, Bus error.
0x00455594 in v8::internal::f64_pow_wrapper(double*, double*) ()
(gdb) backtrace 
warning: GDB can't find the start of the function at 0x553b68d2.

    GDB is unable to find the start of the function at 0x553b68d2
and thus can't determine the size of that function's stack frame.
This means that GDB may be unable to access that stack frame, or
the frames below it.
    This problem is most likely caused by an invalid program counter or
stack pointer.
    However, if you think GDB should simply search farther back
from 0x553b68d2 for code which looks like the beginning of a
function, you can increase the range of the search using the `set
heuristic-fence-post' command.
#0  0x00455594 in v8::internal::f64_pow_wrapper(double*, double*) ()
#1  0x553b68d4 in ?? ()


```

With disabled recovery and in debug mode following output is received with GDB:

```
gdb <PROJECT>/v8/out/mipsel.debug/d8

(gdb) set args --test --random-seed=-849301947 --stress-opt --always-opt --nohard-abort --nodead-code-elimination --nofold-constants --expose-wasm <PROJECT>/v8/test/mjsunit/mjsunit.js <PROJECT>/v8/test/mjsunit/wasm/embenchen/lua_binarytrees.js

(gdb) run
...

============ Stress 1/2 ============

Program received signal SIGBUS, Bus error.
0x01bd47d4 in v8::internal::wasm::AsmWasmBuilderImpl::VisitIfStatement (this=0x7fff571c, stmt=0x2bda520) at ../src/wasm/asm-wasm-builder.cc:203
203 ../src/wasm/asm-wasm-builder.cc: No such file or directory.
(gdb) backtrace
#0  0x01bd47d4 in v8::internal::wasm::AsmWasmBuilderImpl::VisitIfStatement (this=0x7fff571c, stmt=0x2bda520) at ../src/wasm/asm-wasm-builder.cc:203
#1  0x01866420 in v8::internal::IfStatement::Accept (this=0x2bda520, v=0x7fff571c) at ../src/ast/ast.cc:30
#2  0x01bde720 in v8::internal::wasm::AsmWasmBuilderImpl::Visit (this=0x7fff571c, node=0x2bda520) at ../src/wasm/asm-wasm-builder.cc:1750
#3  0x01bd3efc in v8::internal::wasm::AsmWasmBuilderImpl::VisitStatements (this=0x7fff571c, stmts=0x2b4fedc) at ../src/wasm/asm-wasm-builder.cc:148
#4  0x01bd4178 in v8::internal::wasm::AsmWasmBuilderImpl::VisitBlock (this=0x7fff571c, stmt=0x2b4fec0) at ../src/wasm/asm-wasm-builder.cc:167
#5  0x018662d0 in v8::internal::Block::Accept (this=0x2b4fec0, v=0x7fff571c) at ../src/ast/ast.cc:30
#6  0x01bde720 in v8::internal::wasm::AsmWasmBuilderImpl::Visit (this=0x7fff571c, node=0x2b4fec0) at ../src/wasm/asm-wasm-builder.cc:1750
#7  0x01bd6184 in v8::internal::wasm::AsmWasmBuilderImpl::VisitDoWhileStatement (this=0x7fff571c, stmt=0x2b4fe8c) at ../src/wasm/asm-wasm-builder.cc:399
#8  0x01866618 in v8::internal::DoWhileStatement::Accept (this=0x2b4fe8c, v=0x7fff571c) at ../src/ast/ast.cc:30
#9  0x01bde720 in v8::internal::wasm::AsmWasmBuilderImpl::Visit (this=0x7fff571c, node=0x2b4fe8c) at ../src/wasm/asm-wasm-builder.cc:1750
#10 0x01bd3efc in v8::internal::wasm::AsmWasmBuilderImpl::VisitStatements (this=0x7fff571c, stmts=0x2b4d088) at ../src/wasm/asm-wasm-builder.cc:148
#11 0x01bd6d84 in v8::internal::wasm::AsmWasmBuilderImpl::VisitFunctionLiteral (this=0x7fff571c, expr=0x6f2a11dc) at ../src/wasm/asm-wasm-builder.cc:473
#12 0x018668b8 in v8::internal::FunctionLiteral::Accept (this=0x6f2a11dc, v=0x7fff571c) at ../src/ast/ast.cc:30
#13 0x01bde720 in v8::internal::wasm::AsmWasmBuilderImpl::Visit (this=0x7fff571c, node=0x6f2a11dc) at ../src/wasm/asm-wasm-builder.cc:1750
#14 0x01bd3d64 in v8::internal::wasm::AsmWasmBuilderImpl::VisitFunctionDeclaration (this=0x7fff571c, decl=0x6f2a1270) at ../src/wasm/asm-wasm-builder.cc:131
#15 0x018661d4 in v8::internal::FunctionDeclaration::Accept (this=0x6f2a1270, v=0x7fff571c) at ../src/ast/ast.cc:30
#16 0x01bde720 in v8::internal::wasm::AsmWasmBuilderImpl::Visit (this=0x7fff571c, node=0x6f2a1270) at ../src/wasm/asm-wasm-builder.cc:1750
#17 0x01bddca4 in v8::internal::wasm::AsmWasmBuilderImpl::VisitDeclarations (this=0x7fff571c, decls=0x2b22f24) at ../src/wasm/asm-wasm-builder.cc:1626
#18 0x01bd6e10 in v8::internal::wasm::AsmWasmBuilderImpl::VisitFunctionLiteral (this=0x7fff571c, expr=0x6e31a124) at ../src/wasm/asm-wasm-builder.cc:474
#19 0x01bd3b84 in v8::internal::wasm::AsmWasmBuilderImpl::Compile (this=0x7fff571c) at ../src/wasm/asm-wasm-builder.cc:119
#20 0x01bde908 in v8::internal::wasm::AsmWasmBuilder::Run (this=0x7fff5830, foreign_args=0x7fff5c14) at ../src/wasm/asm-wasm-builder.cc:1764
#21 0x0170c048 in v8::(anonymous namespace)::TranslateAsmModule (info=0x7fff5c40, thrower=0x7fff5be4, foreign_args=0x7fff5c14) at ../src/wasm/wasm-js.cc:157
#22 0x0170c7b8 in v8::(anonymous namespace)::InstantiateModuleFromAsm (args=...) at ../src/wasm/wasm-js.cc:228
#23 0x0184fcb0 in v8::internal::FunctionCallbackArguments::Call (this=0x7fff5de4, f=0x170c4fc <v8::(anonymous namespace)::InstantiateModuleFromAsm(v8::FunctionCallbackInfo<v8::Value> const&)>)
    at ../src/api-arguments.cc:16
#24 0x00edecc8 in v8::internal::(anonymous namespace)::HandleApiCallHelper (isolate=0x2aee9c0, args=...) at ../src/builtins.cc:4733
#25 0x00edf11c in v8::internal::Builtin_Impl_HandleApiCall (args=..., isolate=0x2aee9c0) at ../src/builtins.cc:4751
#26 0x00edf0a0 in v8::internal::Builtin_HandleApiCall (warning: GDB can't find the start of the function at 0x3ed0e106.

    GDB is unable to find the start of the function at 0x3ed0e106
and thus can't determine the size of that function's stack frame.
This means that GDB may be unable to access that stack frame, or
the frames below it.
    This problem is most likely caused by an invalid program counter or
stack pointer.
    However, if you think GDB should simply search farther back
from 0x3ed0e106 for code which looks like the beginning of a
function, you can increase the range of the search using the `set
heuristic-fence-post' command.
args_length=6, args_object=0x7fff5ee4, isolate=0x2aee9c0) at ../src/builtins.cc:4748
#27 0x3ed0e108 in ?? ()
(gdb) 
```

**Comment by ilijapavlovic** [comment]
From previous two traces note following lines:

```
warning: GDB can't find the start of the function at 0x553b68d2.
...
warning: GDB can't find the start of the function at 0x3ed0e106.
```

These addresses are not aligned.

**Comment by ilijapavlovic** [comment]
In disassembled code of `AsmWasmBuilderImpl::VisitIfStatement()` there is a line which produces unaligned address:

```
(gdb) disassemble $pc
Dump of assembler code for function v8::internal::wasm::AsmWasmBuilderImpl::VisitIfStatement(v8::internal::IfStatement*):
   ...
   0x01baaf50 <+256>:   lw  v0,72(s8)
   0x01baaf54 <+260>:   lw  v0,60(v0)
   0x01baaf58 <+264>:   move    a0,v0
   0x01baaf5c <+268>:   li  a1,3
   0x01baaf60 <+272>:   jal 0x1bd7ef0 <v8::internal::wasm::WasmFunctionBuilder::Emit(v8::internal::wasm::WasmOpcode)>
   0x01baaf64 <+276>:   nop
   0x01baaf68 <+280>:   lw  v0,72(s8)
   0x01baaf6c <+284>:   addiu   s0,v0,84
=> 0x01baaf70 <+288>:   sw  zero,29(s8)
...
(gdb) info registers s8
s8: 0x7fff5340
(gdb) x /xw $s8+29
0x7fff535d: 0x006de502
```

Note that `29(s8)` gives unaligned address `0x7fff535d`.

In `asm-wasm-builder.cc` there is definition of the function `VisitIfStatement()` :

```
  void VisitIfStatement(IfStatement* stmt) {
    ...
    current_function_builder_->Emit(kExprIf);
    ...
  }
```

Follows investigation of `Emit(kExprIf)`.

**Comment by ilijapavlovic** [comment]
The problem is not in `Emit(kExprIf)`. Consider following code:

```
//
// asm-wasm-builder.cc
//
  void VisitIfStatement(IfStatement* stmt) {
    ...
    current_function_builder_->Emit(kExprIf);
    // WASM ifs come with implement blocks for both arms.
    breakable_blocks_.push_back(std::make_pair(nullptr, false));
    ...
  }
```

For the code above, following assembler code is produced:

```
Dump of assembler code for function v8::internal::wasm::AsmWasmBuilderImpl::VisitIfStatement(v8::internal::IfStatement*):
   ...
   0x01baaf60 <+272>:   jal 0x1bd7ef0 <v8::internal::wasm::WasmFunctionBuilder::Emit(v8::internal::wasm::WasmOpcode)>
   0x01baaf64 <+276>:   nop
   0x01baaf68 <+280>:   lw  v0,72(s8)
   0x01baaf6c <+284>:   addiu   s0,v0,84
   0x01baaf70 <+288>:   sw  zero,29(s8)      // <-- Word unaligned address; 29(s8) == 0x7fff535d
   0x01baaf74 <+292>:   sb  zero,28(s8)
   0x01baaf78 <+296>:   addiu   a0,s8,36
   0x01baaf7c <+300>:   addiu   v1,s8,29
   0x01baaf80 <+304>:   addiu   v0,s8,28
   0x01baaf84 <+308>:   move    a1,v1
   0x01baaf88 <+312>:   move    a2,v0
   0x01baaf8c <+316>:   jal 0x1baad78 <std::make_pair<decltype(nullptr), bool>(std::__decay_and_strip<decltype(nullptr)>&&, decltype(nullptr)<bool>&&)>
   0x01baaf90 <+320>:   nop
   ....
```

Problematical line `sw  zero,29(s8)` is preparation argument for `std::make_pair(nullptr, false)` and refers for **nullptr**. This assembler line is produced by compiler.
If source code is adapted on following way:

```
    ...
    auto null_ptr = nullptr;
    breakable_blocks_.push_back(std::make_pair(null_ptr, false));
    ...
```

then the following assembler code will be produced:

```
=> 0x01bab080 <+280>:   sw  zero,52(s8)      // <----- Word aligned address
   0x01bab084 <+284>:   lw  v0,72(s8)
   0x01bab088 <+288>:   addiu   s0,v0,84
   0x01bab08c <+292>:   sb  zero,28(s8)
   0x01bab090 <+296>:   addiu   a0,s8,32
   0x01bab094 <+300>:   addiu   v1,s8,52
   0x01bab098 <+304>:   addiu   v0,s8,28
   0x01bab09c <+308>:   move    a1,v1
   0x01bab0a0 <+312>:   move    a2,v0
   0x01bab0a4 <+316>:   jal 0x1baae68 <std::make_pair<decltype(nullptr)&, bool>(std::__decay_and_strip<decltype(nullptr)&>&&, decltype(nullptr)&<bool>&&)>
   0x01bab0a8 <+320>:   nop
```

If all lines which contain `std::make_pair(nullptr, false)` are adapted as it is described, new problem will arrive.

```
//
// assembler.cc
//
static void f64_pow_wrapper(double* param0, double* param1) {
  *param0 = power_double_double(*param0, *param1);
}
```

For function `f64_pow_wrapper()` following assembler code is produced:

```
Dump of assembler code for function v8::internal::f64_pow_wrapper(double*, double*):
   0x00e5ea08 <+0>: addiu   sp,sp,-32
   0x00e5ea0c <+4>: sw  ra,28(sp)
   0x00e5ea10 <+8>: sw  s8,24(sp)
   0x00e5ea14 <+12>:    move    s8,sp
   0x00e5ea18 <+16>:    sw  a0,32(s8)
   0x00e5ea1c <+20>:    sw  a1,36(s8)
   0x00e5ea20 <+24>:    lw  v0,32(s8)
=> 0x00e5ea24 <+28>:    ldc1    $f2,0(v0)     <--- NOT DOUBLE-WORD ALIGNED; 0(v0) == 0x7fff5a6c
   0x00e5ea28 <+32>:    lw  v0,36(s8)
   0x00e5ea2c <+36>:    ldc1    $f0,0(v0)
   0x00e5ea30 <+40>:    mov.d   $f12,$f2
   0x00e5ea34 <+44>:    mov.d   $f14,$f0
   0x00e5ea38 <+48>:    jal 0xe60148 <v8::internal::power_double_double(double, double)>
   0x00e5ea3c <+52>:    nop
   0x00e5ea40 <+56>:    lw  v0,32(s8)
   0x00e5ea44 <+60>:    sdc1    $f0,0(v0)
   0x00e5ea48 <+64>:    move    sp,s8
   0x00e5ea4c <+68>:    lw  ra,28(sp)
   0x00e5ea50 <+72>:    lw  s8,24(sp)
   0x00e5ea54 <+76>:    addiu   sp,sp,32
   0x00e5ea58 <+80>:    jr  ra
   0x00e5ea5c <+84>:    nop
End of assembler dump.
```

For `ldc1`instruction, following is mentioned in the specification:

> Restrictions:
> Pre-Release 6: An Address Error exception occurs if EffectiveAddress 2..0 ≠ 0 (not doubleword-aligned).

In this case, `ldc1` instruction has double-word unaligned address `0x7fff5a6c` which is produced also by compiler.

**Comment by ilijapavlovic** [comment]
This is small example for reproducing word unaligned address and "bus error":

```
//
// test_unaligned_word_address.cc
//
#include <utility>
#include <sys/sysmips.h>

int main() {
  sysmips(MIPS_FIXADE, 0);
  auto res = std::make_pair(nullptr, false);
  return 0;
}
```

Compile with command:

```
<PROJECT>/MIPS/toolchains/mips-mti-linux-gnu/2015.01-7/bin/mips-mti-linux-gnu-g++ -mips32r2 -EL -mfp32 -g -O0 -std=gnu++0x -static <PROJECT>/MIPS/examples/test_unaligned_word_address.cc -o <PROJECT>/MIPS/examples/test_unaligned_word_address
```

Produced assembler code:

```
(gdb) disassemble $pc
Dump of assembler code for function main():
   0x00400cd0 <+0>: addiu   sp,sp,-48
   0x00400cd4 <+4>: sw  ra,44(sp)
   0x00400cd8 <+8>: sw  s8,40(sp)
   0x00400cdc <+12>:    move    s8,sp
   0x00400ce0 <+16>:    li  a0,7
   0x00400ce4 <+20>:    move    a1,zero
   0x00400ce8 <+24>:    jal 0x41c2e8 <sysmips>
   0x00400cec <+28>:    nop
=> 0x00400cf0 <+32>:    sw  zero,25(s8)       // <--- Unaligned word address 0x7fff6569
   0x00400cf4 <+36>:    sb  zero,24(s8)
   0x00400cf8 <+40>:    addiu   v1,s8,32
   0x00400cfc <+44>:    addiu   v0,s8,25
   0x00400d00 <+48>:    move    a0,v1
   0x00400d04 <+52>:    move    a1,v0
   0x00400d08 <+56>:    addiu   v0,s8,24
   0x00400d0c <+60>:    move    a2,v0
   0x00400d10 <+64>:    jal 0x400dfc <std::make_pair<decltype(nullptr), bool>(std::__decay_and_strip<decltype(nullptr)>&&, decltype(nullptr)<bool>&&)>
   0x00400d14 <+68>:    nop
   0x00400d18 <+72>:    move    v0,zero
   0x00400d1c <+76>:    move    sp,s8
   0x00400d20 <+80>:    lw  ra,44(sp)
   0x00400d24 <+84>:    lw  s8,40(sp)
   0x00400d28 <+88>:    addiu   sp,sp,48
   0x00400d2c <+92>:    jr  ra
   0x00400d30 <+96>:    nop
End of assembler dump.
(gdb) x /xw $s8+25
0x7fff6569: 0xbc005258
```

**Comment by kilvadyb** [comment]
Nice catch. The nullptr thing looks like a compiler bug. could you test it with different/newer GCCs (5, 5.x) and/or with clang?

The ldc1 failure is not a compiler generated bug but, I guess, param0 or param1 points to an unaligned address. In fullcodegen and crankshaft we fixed this kind of double read/write problems with [READ|WRITE]_DOUBLE_FIELD macros which calls [Read|Write]DoubleValue() inline functions from src/utils.h. Could/Should we use them here (or everywhere in wasm and turbofan)?

**Comment by kilvadyb** [comment]
In the `ldc1` case we should check where param0 and param1 come from and could we ensure  8 bytes alignment or (from wasm specs) using [Read|Write]DoubleValue() functions is necessary.

**Comment by ilijapavlovic** [comment]
These results are received with GCC. Clang is also tested and the result was the same: "buss error". I will try to reproduce the problem with double word unaligned address.

**Comment by kilvadyb** [comment]
Does the nullptr case fail with clang also? Very strange,
`sw  zero,25(s8)       // <--- Unaligned word address 0x7fff6569`
is quite buggy. And from 2 different compilers... In this case we should send a well documented bugreport with objdumps to the imgtec compiler team(s). Could you get asm/debug code of clang compiling the small nullptr sample program (in the same form as the GCC result)? We can discuss it on the meeting and pass the findings to imgtec people.

**Comment by ilijapavlovic** [comment]
For `ldc1`: I couldn't determine who made calling of the `f64_call_wrapper()`:

```
(gdb) backtrace
#0  0x00e5ea18 in v8::internal::f64_pow_wrapper (param0=0x504068, param1=0x3d88) at ../src/assembler.cc:1347
#1  0x553b0ef4 in ?? ()
```

Disassebmling location #1 was not possible.

```
(gdb) backtrace
#0  0x00e5e9c4 in v8::internal::f64_pow_wrapper (param0=0x7fff5a6c, param1=0x7fff5a74) at ../src/assembler.cc:1348
#1  0x553b0ef4 in ?? ()
(gdb) disassemble 0x553b0ef4
No function contains specified address.
```

I will check again for nullptr case and clang compiler.

Ok - I'll try to make also compiling small example for nullptr with clang.

**Comment by kilvadyb** [comment]
In gdb: location 1 can't be disasmed because it is called from generated v8 asm code not from a C function, I guess. You can try x/16i 0x553b0ef4 - 16 for example.

**Comment by ilijapavlovic** [comment]
For testing nullptr, use following command for compiling with clang:

```
<PROJECT>/MIPS/v8/third_party/llvm-build/Release+Asserts/bin/clang++  --target=mipsel-linux-gnu -stdlib=libstdc++ --gcc-toolchain=<PROJECT>/MIPS/toolchains/mips-mti-linux-gnu/2015.01-7 -mips32r2 -EL -mfp32 -g -O0 -std=gnu++0x -static <PROJECT>/MIPS/examples/test_unaligned_word_address.cc -o <PROJECT>/MIPS/examples/test_unaligned_word_address
```

Assembler code produced with Clang compiler seems OK:

```
(gdb) disassemble $pc
Dump of assembler code for function main():
   0x00400d50 <+0>: addiu   sp,sp,-56
   0x00400d54 <+4>: sw  ra,52(sp)
   0x00400d58 <+8>: sw  s8,48(sp)
   0x00400d5c <+12>:    move    s8,sp
   0x00400d60 <+16>:    sw  zero,44(s8)
   0x00400d64 <+20>:    li  a0,7
   0x00400d68 <+24>:    li  at,0
   0x00400d6c <+28>:    move    a1,at
   0x00400d70 <+32>:    sw  at,20(s8)
   0x00400d74 <+36>:    jal 0x41c368 <sysmips>
   0x00400d78 <+40>:    nop
=> 0x00400d7c <+44>:    sw  zero,28(s8)   // <--- word aligned address 28(s8) == 0x7fff6564
   0x00400d80 <+48>:    sb  zero,24(s8)
   0x00400d84 <+52>:    addiu   a0,s8,32
   0x00400d88 <+56>:    addiu   a1,s8,28
   0x00400d8c <+60>:    addiu   a2,s8,24
   0x00400d90 <+64>:    sw  v0,16(s8)
   0x00400d94 <+68>:    jal 0x400db8 <std::make_pair<decltype(nullptr), bool>(decltype(nullptr)&&, bool&&)>
   0x00400d98 <+72>:    nop
   0x00400d9c <+76>:    lw  v0,20(s8)
   0x00400da0 <+80>:    move    sp,s8
   0x00400da4 <+84>:    lw  s8,48(sp)
   0x00400da8 <+88>:    lw  ra,52(sp)
   0x00400dac <+92>:    addiu   sp,sp,56
   0x00400db0 <+96>:    jr  ra
   0x00400db4 <+100>:   nop
End of assembler dump.
(gdb) x /xw $s8+28
0x7fff6564: 0x00401590
```

**Comment by kilvadyb** [comment]
Even better, we can show to the compiler team how GCC fails and clang is right :) Tough it should be tested/dumped with the latest imgtec GCC toolchain.

**Comment by kilvadyb** [comment]
I did some debugging and code analyzis. I think if we introduce new type (and field in StoreRepresentation ?) then in `InstructionSelector::VisitStore()` we could do double alignment but I don't see any speed improvement to Ivica's CL: https://codereview.chromium.org/2034523003/ (that would complicate push (one more instruction) and we would have trouble at pop - stack unwinding.

**Comment by ilijapavlovic** [comment]
The problem about nullptr is reported to GCC team. They created an internal ticket #2360.

**Comment by ibogosavljevic** [comment]
Fixed by CL:
https://codereview.chromium.org/2034523003/

https://v8.mips.com/bbv8/builders/Target%20-%20edge/builds/7361/steps/Check/logs/stdio

Closing...

**Comment by palfia** [comment]
Sometimes it still fails on R6 Sim: https://v8.mips.com/bbv8/builders/Sim%20-%20edge%20-%20mipsr6/builds/2584
